rules:
  # Disables a11y issues for testing
  html-has-lang: false 
exclude:
  - packages/react/CHANGELOG.md
  - packages/react/examples/**/*
  - packages/react/cypress/**/*
  - packages/cli/test/**/*
  - packages/cli/testutils/**/*
