version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'chore'
    groups:
      # Any updates not caught by the group config will get individual PRs
      gha-low-risk:
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'chore'
    ignore:
      # Handled separately by its own workflow
      - dependency-name: '@axe-core/*'
      - dependency-name: 'axe-core'
      # Prevent updates to ESM-only versions
      - dependency-name: 'execa'
        versions: ['>=6.0.0']
      - dependency-name: 'node-fetch'
        versions: ['>=3.0.0']
      - dependency-name: 'delay'
        versions: ['>=6.0.0']
      - dependency-name: 'tempy'
        versions: ['>=2.0.0']
      # Breaking change due to node version requirements
      - dependency-name: 'commander'
        versions: ['>=10.0.0']
    groups:
      # Any updates not caught by the group config will get individual PRs
      npm-low-risk:
        update-types:
          - 'minor'
          - 'patch'
