contact_links:
  - name: Join the axe Slack Community
    url: https://accessibility.deque.com/axe-community
    about: Connect with other people passionate about digital accessibility and axe tools.
