name: Improve our documentation
description: Report issues in our documentation or things we could document better.
labels: ['docs', 'ungroomed']
body:
  - type: markdown
    attributes:
      value: |
        Documentation reports can be made for axe-core npm integrations (e.g. `@axe-core/webdriverjs`).
  - type: dropdown
    id: product
    attributes:
      label: Product
      description: Which product is the documentation report for?
      options:
        - cli
        - playwright
        - puppeteer
        - react
        - reporter-earl
        - webdriverio
        - webdriverjs
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
