version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    default_labels:
      - "axe_api_deps_bot"
  - package_manager: "javascript"
    directory: "/axe_core_test"
    update_schedule: "weekly"
    default_labels:
      - "axe_api_deps_bot"
  - package_manager: "javascript"
    directory: "/packages/cli"
    update_schedule: "weekly"
    default_labels:
      - "axe_api_deps_bot"
  - package_manager: "javascript"
    directory: "/packages/puppeteer"
    update_schedule: "weekly"
    default_labels:
      - "axe_api_deps_bot"
  - package_manager: "javascript"
    directory: "/packages/react"
    update_schedule: "weekly"
    default_labels:
      - "axe_api_deps_bot"
  - package_manager: "javascript"
    directory: "/packages/reporter-earl"
    update_schedule: "weekly"
    default_labels:
      - "axe_api_deps_bot"
  - package_manager: "javascript"
    directory: "/packages/webdriverjs"
    update_schedule: "weekly"
    default_labels:
      - "axe_api_deps_bot"