name: Create release candidate

on: pull_request

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: manifest
          monorepo-tags: true
          release-type: node
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
        if: ${{ steps.release.outputs.releases_created }}
