name: Create release candidate

on: pull_request

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - name: Create release commit
        run: |
          Branch="release-$(date +%Y-%m-%d)"
          git config user.name "${{ secrets.ADT_API_RELEASE_NAME }}"
          git config user.email "${{ secrets.ADT_API_RELEASE_EMAIL }}"

          git checkout -b "$Branch"

          npm run release -- --release-as patch

          git push --follow-tags origin "$Branch" --force

          Version=$(jq -r .version ./package.json)

          ReleaseNotes=$(
            git show \
              --no-color \
              --no-prefix \
              --output-indicator-new=! CHANGELOG.md | egrep '^!' | awk -F'^[!]' '{print $2}' | sed -e 's/\n/$0A/g'
          )

          echo "chore(release): v$Version" > /tmp/pr.txt
          echo "" >> /tmp/pr.txt
          echo "$ReleaseNotes" >> /tmp/pr.txt
          echo "" >> /tmp/pr.txt
          echo "This PR was opened by a robot :robot: :tada:" >> /tmp/pr.txt

          hub pull-request --file /tmp/pr.txt --base master
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
