name: Create release candidate 

on:
  workflow_dispatch:
    inputs:
      version-locked:
        type: boolean
        description: Prevent this action from creating a minor or major release
        default: true

jobs:
  create-release-candidate:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0
        with:
          standalone: true
      - uses: dequelabs/axe-api-team-public/.github/actions/create-release-candidate-v1@main
        with:
          token: ${{ secrets.PAT }}
          base: 'master'
          head: 'develop'
          release-script-path: './.github/scripts/prepare_release.sh'
          version-locked: ${{ inputs.version-locked }}
          should-checkout: false
        env:
          GH_TOKEN: ${{ secrets.GH_PROJECT_TOKEN }}
