name: Create release candidate 

on:
  workflow_dispatch:
    inputs:
      version-locked:
        type: boolean
        description: Prevent this action from creating a minor or major release
        default: true

jobs:
  create-release-candidate:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: dequelabs/axe-api-team-public/.github/actions/create-release-candidate-v1@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: 'master'
          head: 'develop'
          release-script-path: './.github/scripts/prepare_release.sh'
          version-locked: ${{ inputs.version-locked }}
        env:
          GH_TOKEN: ${{ secrets.GH_PROJECT_TOKEN }}
