name: Deploy

on:
  push:
    branches:
      - develop
      - master

jobs:
  canary:
    runs-on: ubuntu-latest
    if: github.ref_name == 'develop'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run bootstrap
      # Make sure the working tree is clean
      - run: git reset --hard HEAD
      - run: |
          npx lerna publish prepatch \
            --no-verify-access \
            --no-git-tag-version \
            --no-push \
            --canary \
            --dist-tag=next \
            --exact \
            --force-publish \
            --yes

  production:
    runs-on: ubuntu-latest
    if: github.ref_name == 'master'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run bootstrap
      # Make sure the working tree is clean
      - run: git reset --hard HEAD
      - run: |
          npx lerna publish from-package \
            --force-publish='*' \
            --yes
      - uses: softprops/action-gh-release@v1
