name: Generate Commit List

on: [push]

jobs:
  another-thing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Debug Git
        run: |
          echo "Current Commit: $(git rev-parse HEAD)"
          echo "Origin Master: $(git rev-parse origin/master)"
  generate-commit-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dequelabs/axe-api-team-public/.github/actions/generate-commit-list-v1@ec22a97ba476bff5b6aab6a240944b1749545dd3
        id: generate-commit-list
        with:
          base: master
          head: develop
      - name: Print commit list
        run: echo "${{ steps.generate-commit-list.outputs.commit-list }}"
