name: Sync master/develop branches

on:
  pull_request:
    types: [closed]
    branches: master

jobs:
  create_sync_pull_request:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: dequelabs/action-sync-branches@v1
        with:
          github-token: ${{ secrets.PAT }}
          pr-title: 'chore: merge master into develop'
          pr-team-reviewers: axe-api-team
          pr-labels: chore
