name: Sync master/develop branches

on:
  pull_request:
    types: [closed]
    branches: master

jobs:
  create_sync_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: dequelabs/action-sync-branches@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-title: "chore: merge master into develop"
          pr-reviewers: michael-siek,stephenmathieson
          pr-labels: chore
          pr-template: .github/PULL_REQUEST_TEMPLATE.md
