name: Tests

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run bootstrap -- --ci
      - run: npm run lint

  puppeteer:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - run: npm run build --prefix=packages/puppeteer
      - run: npx browser-driver-manager install chrome chromedriver --verbose
      - run: npm run coverage --prefix=packages/puppeteer
      - run: npm run test:esm --prefix=packages/puppeteer

  cli:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      # Re-build packages, ensuring packages/webdriverjs/dist exists.
      - run: npx lerna run prepare
      - run: npx browser-driver-manager install chrome chromedriver --verbose
      # lerna link after installing the latest version of chromedriver, as we depend on webdriverJS
      - run: npx lerna link
        working-directory: packages/cli
      - run: npm run coverage --prefix=packages/cli

  webdriverjs:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - run: npm run build --prefix=packages/webdriverjs
      - run: npx browser-driver-manager install chrome chromedriver --verbose
      - run: npm run coverage --prefix=packages/webdriverjs
        env:
          CHROMEDRIVER_PATH: /usr/local/bin/chromedriver
      - run: npm run test:esm --prefix=packages/webdriverjs
        env:
          CHROMEDRIVER_PATH: /usr/local/bin/chromedriver

  webdriverio:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - run: npm run build --prefix=packages/webdriverio
      - run: npx browser-driver-manager install chrome chromedriver --verbose
      - run: npm run coverage --prefix=packages/webdriverio
        env:
          CHROMEDRIVER_PATH: /usr/local/bin/chromedriver
      - run: npm run test:esm --prefix=packages/webdriverio
        env:
          CHROMEDRIVER_PATH: /usr/local/bin/chromedriver

  reporter_earl:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - run: npm run bootstrap -- --ci
      - run: npm run build --prefix=packages/reporter-earl
      - run: npm run test --prefix=packages/reporter-earl
      - run: npm run test:esm --prefix=packages/reporter-earl
